# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequence_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(151, 331)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(0, 90, 151, 201))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 300, 151, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 30, 151, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(0, 0, 151, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(0, 60, 151, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "预览"))
        self.comboBox_2.setItemText(0, _translate("Form", "顺序"))
        self.comboBox_2.setItemText(1, _translate("Form", "逆序"))
        self.comboBox.setItemText(0, _translate("Form", "所有文件"))
        self.comboBox.setItemText(1, _translate("Form", "当前文件"))
        self.comboBox.setItemText(2, _translate("Form", "选中文件"))
        self.comboBox_3.setItemText(0, _translate("Form", "名称+序号"))
        self.comboBox_3.setItemText(1, _translate("Form", "名称+序号(自动补全)"))
        self.comboBox_3.setItemText(2, _translate("Form", "仅序号"))
        self.comboBox_3.setItemText(3, _translate("Form", "仅序号(自动补全)"))
        self.comboBox_3.setItemText(4, _translate("Form", "自定义"))
